version: '3.8'

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - type: bind 
        source: ./database
        target: /var/lib/postgresql/data
    

  backend:
    image: example-backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - db
  
  frontend:
    image: example-frontend
    ports:
      - "5000:5000"
  
  redis:
    image: redis:7.0.15-alpine
