version: '3.8'

networks:
  internal-network:
    name: internal-network

services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - internal-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend


  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - internal-network
    volumes:
      - type: bind 
        source: ./database
        target: /var/lib/postgresql/data
    

  backend:
    image: example-backend:latest
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - db
    expose:
      - "8080"
    networks:
      - internal-network
  
  frontend:
    image: example-frontend
    expose:
      - "5000"
    networks:
      - internal-network
  
  redis:
    image: redis:7.0.15-alpine
    networks:
      - internal-network
 